apiVersion: apps/v1
kind: Deployment
metadata:
  name: myphp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myphp
  template:
    metadata:
      labels:
        app: myphp
    spec:
      containers:
        - name: myphp
          image: http://3.96.203.160:8082/myphpapp:1.13
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: myphp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: php